### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by mansya** [mars/heroku-app-with-vault#1]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by mars** [comment]
Thanks for the offer, but this repo is a failed experiment 😔

**Comment by hotmeteor** [comment]
@mars Does this approach not work? I'm looking for a way to use Vault with Heroku.

**Comment by mars** [comment]
@hotmeteor I definitely don't recommend using any of this experimental Vault + Heroku stuff. There's no clean, secure way to do it.

At the core of it, you have to set Vault keys into Heroku config vars, and really there's no added security there, just complexity.

**Comment by hotmeteor** [comment]
Man, that's a shame. It's my #1 gripe with Heroku, that you basically have to have zero access to an app if you want to secure the keys. Did you come up with any other ideas?

**Comment by mars** [comment]
Config vars are the only secrets mechanism on Heroku.
